# Compose file to launch my apps relying on Traefik
#   - MyJoplin
#   - Zoneminder
#   - MyNextcloud

include:
  - path: '../MyTraefik/docker-compose.yml'
  - path: '../MyJoplin/docker-compose.yml'
  - path: '../zoneminder/docker-compose.yml'
  - path: '../MyNextCloud/docker-compose.yml'

